# Generated by Django 5.2.8 on 2025-11-10 21:57

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body_md', models.TextField()),
                ('tags_csv', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.models.blog_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('citation', models.TextField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=core.models.research_pdf_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='in_progress', max_length=20)),
                ('tags_csv', models.CharField(blank=True, help_text='comma-separated tags', max_length=400)),
                ('tech_stack_csv', models.CharField(blank=True, help_text='comma-separated tech', max_length=500)),
                ('highlights_csv', models.TextField(blank=True, help_text='one per line')),
                ('abstract', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.models.project_image_path)),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
