# Generated by Django 5.2.8 on 2025-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certification_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='body_md',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Lincoln', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='Pending', help_text='Markdown content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If checked, this will be the main download.'),
        ),
    ]
