# Generated by Django 6.0 on 2025-12-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_education_experience_sitesetting_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload PDF resume (overrides external link)', null=True, upload_to='resumes/'),
        ),
    ]
